#remote_theme: jekyll/minima
#minima:
#  skin: auto
plugins:
- jekyll-remote-theme
remote_theme: "dracula/gh-pages"
title: "LPDU"
description: "Strats used on Light DC"
show_downloads: false
show_header: false
